//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DataLayar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagement_DBEntities : DbContext
    {
        public LibraryManagement_DBEntities()
            : base("name=LibraryManagement_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Members> tb_Members { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Books> tb_Books { get; set; }
        public virtual DbSet<tb_BooksStatus1> tb_BooksStatus1Set { get; set; }
        public virtual DbSet<tb_Login> tb_Login { get; set; }
    }
}
