//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DataLayar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Books
    {
        public int bookID { get; set; }
        public string bookName { get; set; }
        public string bookWriter { get; set; }
        public string bookSubject { get; set; }
        public string bookPublishDate { get; set; }
    }
}
