//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.DataLayar
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Members
    {
        public int memberID { get; set; }
        public string memberName { get; set; }
        public string memberLastName { get; set; }
        public string memberPhone { get; set; }
        public string membershipDate { get; set; }
    }
}
